source "https://rubygems.org"

ruby "3.2.9"

# ===== Rails Core =====
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "rails", "~> 7.2.0"

# HTML / JSON
gem "jbuilder", "~> 2.12"

# Boot speed
gem "bootsnap", require: false

# Security patches for indirect dependencies
gem "nokogiri", "~> 1.18"
gem "rack", "~> 3.2"
gem "rack-cors", "~> 2.0"
gem "rails-html-sanitizer", "~> 1.6"
gem "rexml", "~> 3.3"

gem "cgi", "~> 0.4.0"

# ===== Development & Test =====
group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.2"
  gem "rspec-rails", "~> 6.1"

  # Linting
  gem "rubocop", "~> 1.59", require: false
  gem "rubocop-rails", "~> 2.23", require: false
  gem "rubocop-rspec", "~> 2.26", require: false
end

group :development do
  # Code reload
  gem "spring"
  gem "spring-commands-rspec"

  # Security auditing
  gem "brakeman", require: false
  gem "bundler-audit", require: false
end

group :test do
  gem "database_cleaner-active_record", "~> 2.1"
  gem "shoulda-matchers", "~> 6.0"
  gem "simplecov", require: false
end
